version: "3.8"
services:
  authenticator:
    image: fede0104/virtual-wallet-app:authenticator-latest
    ports:
      - "8081:8091"
    environment:
      - PROFILE=prod
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - MS_USERS_BASE_URL=http://USERS/api/users
      - MS_USERS_CREDENTIALS=USER_SECRET_REST:PASS_SECRET_REST
    networks:
      - backend-net

  users:
    image: fede0104/virtual-wallet-app:users-latest
    ports:
      - "8082:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - DB_URL=jdbc:mysql://db-users:3306/usersdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_USER=usersuser
      - DB_PASSWORD=userspass
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - CREDENTIALS_USER=USER_SECRET_REST
      - CREDENTIALS_PASS=PASS_SECRET_REST
    networks:
      - backend-net

  accounts:
    image: fede0104/virtual-wallet-app:accounts-latest
    ports:
      - "8083:8093"
    environment:
      - PROFILE=prod
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - DB_URL=jdbc:mysql://db-accounts:3306/accountsdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_USER=accountsuser
      - DB_PASSWORD=accountspass
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - CREDENTIALS_USER=USER_SECRET_REST
      - CREDENTIALS_PASS=PASS_SECRET_REST
    networks:
      - backend-net

  transacciones:
    image: fede0104/virtual-wallet-app:transacciones-latest
    ports:
      - "8084:8094"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
      - DB_URL=jdbc:mysql://db-transactions:3306/transactionsdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_USER=txuser
      - DB_PASSWORD=txpass
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - CREDENTIALS_USER=USER_SECRET_REST
      - CREDENTIALS_PASS=PASS_SECRET_REST
    networks:
      - backend-net


networks:
  backend-net:
    driver: bridge