# Creates and runs containers for each microservice image published on Docker Hub.

services:
  authenticator:
    container_name: ${AUTHENTICATOR_CONTAINER_NAME}
    image: fede0104/virtual-wallet-app:authenticator-latest
    ports:
      - ${AUTH_HOST_PORT}:${AUTH_CONTAINER_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MS_USERS_BASE_URL=${MS_USERS_BASE_URL}
      - MS_USERS_CREDENTIALS=${MS_USERS_CREDENTIALS}
      - x-environment
      - CREDENTIALS_USER=USER_SECRET_REST
      - CREDENTIALS_PASS=PASS_SECRET_REST
    networks:
      - backend-net

  users:
    container_name: ${USERS_CONTAINER_NAME}
    image: fede0104/virtual-wallet-app:users-latest
    ports:
      - ${USERS_HOST_PORT}:${USERS_CONTAINER_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_URL=${DB_USERS_URL}
      - DB_DRIVER=${DB_USERS_DRIVER}
      - DB_USER=${DB_USERS_USER}
      - DB_PASSWORD=${DB_USERS_PASS}
      - CREDENTIALS_USER=${USERS_CREDENTIALS_USER}
      - CREDENTIALS_PASS=${USERS_CREDENTIALS_PASS}
    networks:
      - backend-net
      - database-net

  accounts:
    container_name: ${ACCOUNTS_CONTAINER_NAME}
    image: fede0104/virtual-wallet-app:accounts-latest
    ports:
      - ${ACCOUNTS_HOST_PORT}:${ACCOUNTS_CONTAINER_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_URL=${DB_ACCOUNTS_URL}
      - DB_DRIVER=${DB_ACCOUNTS_DRIVER}
      - DB_USER=${DB_ACCOUNTS_USER}
      - DB_PASSWORD=${DB_ACCOUNTS_PASS}
      - CREDENTIALS_USER=${ACCOUNTS_CREDENTIALS_USER}
      - CREDENTIALS_PASS=${ACCOUNTS_CREDENTIALS_PASS}
    networks:
      - backend-net
      - database-net

  transacciones:
    container_name: ${TRANSACTIONS_CONTAINER_NAME}
    image: fede0104/virtual-wallet-app:transacciones-latest
    ports:
      - ${TRANSACTIONS_HOST_PORT}:${TRANSACTIONS_CONTAINER_PORT}
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://db-transactions:3306/transactionsdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_USER=txuser
      - DB_PASSWORD=txpass
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - CREDENTIALS_USER=USER_SECRET_REST
      - CREDENTIALS_PASS=PASS_SECRET_REST
    networks:
      - backend-net
      - database-net

networks:
  backend-net:
    driver: bridge
    name: ${BACKEND_NET_NAME}
  database-net:
    driver: bridge