jwt:
  secret: ${JWT_SECRET}
  duration-minutes: ${JWT_SECRET_DURATION}

  microservices:
    users:
      base-url: ${MS_USERS_BASE_URL}
      credentials: ${MS_USERS_CREDENTIALS}
    transactions:
      base-url: ${MS_TRANSACTIONS_BASE_URL}
      credentials: ${MS_TRANSACTIONS_CREDENTIALS}
    accounts:
      base-url: ${MS_ACCOUNTS_BASE_URL}
      credentials: ${MS_ACCOUNTS_CREDENTIALS}