#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3310/usersdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: usersuser
#    password: userspass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect

spring:
  application:
    name: users

  datasource:
    url: jdbc:mysql://localhost:3310/usersdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: usersuser
    password: userspass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

my:
  custom:
    message: "Hola desde Config Server - users dev"

