spring:
  datasource:
    url: jdbc:mysql://localhost:3312/transactionsdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: txuser
    password: txpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: myXlocalXdevXsecretXkeyX32XcharsXminWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
  duration-minutes: 10

microservices:
  users:
    base-url: http://USERS/api
    credentials: '1:1' #user:pass
  accounts:
    base-url: http://ACCOUNTS/api/accounts
    credentials: '1:1' #user:pass
  transactions:
    base-url: http://TRANSACTIONS/api/transactions
    credentials: '1:1' #user:pass
  auth:
    base-url: http://AUTH/api/auth
#    credentials: '1:1' #user:pass
