name: CI Pipeline Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [authenticator, users, accounts, transacciones]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for Gradle wrapper ${{ matrix.service }}
        run: chmod +x ./backend/${{ matrix.service }}/gradlew

      - name: Build & Test ${{ matrix.service }}
        run: |
          cd ./backend/${{ matrix.service }}
          ./gradlew clean build test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image ${{ matrix.service }}
        run: docker build -t fede0104/virtual-wallet-app:${{ matrix.service }}-latest ./backend/${{ matrix.service }}

      - name: Push Docker image ${{ matrix.service }}
        run: docker push fede0104/virtual-wallet-app:${{ matrix.service }}-latest
