name: CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AuthenticatorMs, users, accounts, transactions]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for Gradle wrapper ${{ matrix.service }}
        run: chmod +x ./backend/${{ matrix.service }}/gradlew

      - name: Build & Test ${{ matrix.service }}
        run: |
          cd ./backend/${{ matrix.service }}
          ./gradlew clean build test

      - name: Build Docker image ${{ matrix.service }}
        run: |
          docker build -t mydockerhubusername/${{ matrix.service }}:latest ./backend/${{ matrix.service }}
